#!/usr/bin/env bash

mkdir -p $HOME/bin

sudo pacman -S --noconfirm --needed linux-headers
yay -S --noconfirm --needed go 
yay -S --noconfirm --needed sbt 
yay -S --noconfirm --needed rustup 
yay -S --noconfirm --needed jdk-openjdk 
yay -S --noconfirm --needed tmux 
yay -S --noconfirm --needed thefuck 
yay -S --noconfirm --needed zplug 
yay -S --noconfirm --needed zsh 
yay -S --noconfirm --needed zsh-syntax-highlighting 
yay -S --noconfirm --needed zsh-theme-powerlevel10k 
yay -S --noconfirm --needed oh-my-zsh-git 
yay -S --noconfirm --needed terminator 
yay -S --noconfirm --needed visual-studio-code-bin 
yay -S --noconfirm --needed jetbrains-toolbox 
yay -S --noconfirm --needed vim 
yay -S --noconfirm --needed numix-circle-arc-icons-git 
yay -S --noconfirm --needed xorg-xrandr 
yay -S --noconfirm --needed restic 
yay -S --noconfirm --needed remmina 
yay -S --noconfirm --needed freerdp 
yay -S --noconfirm --needed nxproxy 
yay -S --noconfirm --needed lastpass-cli 
yay -S --noconfirm --needed xclip 
yay -S --noconfirm --needed docker 
yay -S --noconfirm --needed docker-compose 
yay -S --noconfirm --needed pass 
yay -S --noconfirm --needed libu2f-host 
yay -S --noconfirm --needed dropbox-cli 
yay -S --noconfirm --needed rescuetime2 
yay -S --noconfirm --needed gitflow-avh 
yay -S --noconfirm --needed gitflow-zshcompletion-avh 
yay -S --noconfirm --needed sublime-text
yay -S --noconfirm --needed tomb 
yay -S --noconfirm --needed system-san-francisco-font-git 
yay -S --noconfirm --needed otf-san-francisco-pro 
yay -S --noconfirm --needed otf-san-francisco-mono 
yay -S --noconfirm --needed powerline 
yay -S --noconfirm --needed powerline-fonts 
yay -S --noconfirm --needed fzf 
yay -S --noconfirm --needed npm 
yay -S --noconfirm --needed gmrun 
yay -S --noconfirm --needed dotnet-sdk 
yay -S --noconfirm --needed neofetch 
yay -S --noconfirm --needed lldb 
yay -S --noconfirm --needed awesome-terminal-fonts 
yay -S --noconfirm --needed pigz
yay -S --noconfirm --needed task
yay -S --noconfirm --needed polybar
yay -S --noconfirm --needed udiskie
yay -S --noconfirm --needed jq
yay -S --noconfirm --needed xdotool
yay -S --noconfirm --needed autorandr
yay -S --noconfirm --needed nordvpn
yay -S --noconfirm --needed polybar-scripts-git
yay -S --noconfirm --needed kitty
yay -S --noconfirm --needed slack-desktop
yay -S --noconfirm --needed whatsapp-nativefier
yay -S --noconfirm --needed signal-desktop
yay -S --noconfirm --needed betterlockscreen
yay -S --noconfirm --needed simplenote-electron-bin
yay -S --noconfirm --needed telegram-desktop
yay -S --noconfirm --needed arandr
yay -S --noconfirm --needed solaar
