#!/usr/bin/env bash

source $HOME/.restic.env

restic -r /restic/repo backup --verbose --files-from $HOME/bin/restic-backup-files
restic -r /restic/repo forget --keep-last=3 --keep-daily 1 --keep-weekly 1 --keep-monthly 1 --prune
